### ISSUE TITLE
A Guessing Game

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#13]
_This is assignment 13 and is due on Feb 02, 2015._

* Create a guessing game
* The user must guess the number chosen by the app
* Provide feedback to the user as to if their guess is lower or higher than the number
* Count the number of guesses and output at the end

**Comment by brianburridge** [comment]
So, :+1: for adding the user chosen range as extra functionality.

Keep in mind that when Ruby goes through if/thens it will stop as soon as it finds a match and not go any further. So, if the first check was to see if it's outside the top number, and that's where you told them that, it wouldn't have to check for being outside the range on all the other conditions.

**Comment by DianaDryerDavis** [comment]
D'oh! That's so simple. Why didn't I think of that?

It's fixed now. Thanks!

**Comment by brianburridge** [comment]
Looks good!
