### ISSUE TITLE
Extending String with PigLatin

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#20]
_This is assignment 19 and is due on Feb 04, 2015._

Extend Ruby's String class to have a "pigatize" method that will turn any string into pig latin.

Should use the same code you wrote before, but now you are extending the String class and putting the functionality in there.

**Comment by brianburridge** [comment]
Hey Diana. Let's talk about this assignment tomorrow. There are a couple of issues that will be easier to discuss in person.

**Comment by DianaDryerDavis** [comment]
Well, shoot. I decided that I'd gone down the wrong path, so I deleted everything from yesterday and started over tonight. Sounds like this path was even more wrong!

**Comment by DianaDryerDavis** [comment]
Turns out I was on the right path the first time around but didn't go far enough with the self/passed text shift. It's fixed now.

**Comment by brianburridge** [comment]
So, yes, you fixed the method part. Only issue now is that you have the code to demonstrate the pigatize method inside the String class itself. That means that anytime a developer loads your extension to use it, they'll get prompted. :)

**Comment by DianaDryerDavis** [comment]
Grr. I left it there just to test it and in my jubilation over finding it worked, I forgot to wipe it out! It's fixed now.

**Comment by brianburridge** [comment]
:+1:
