### ISSUE TITLE
Validations and Associations

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#35]
_This is assignment 34 and is due on Feb 19, 2015._

* [Read Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html)
* [Read Active Record Associations](http://guides.rubyonrails.org/association_basics.html)
* Continuing with your app from assignment 33, add a second model (use the migration generator) and use a _reference_ and _belongs_to/has_many_ relationship.
* Also add at least three validations between the two models.
* Test your model relationships in the rails console to be sure they work.

**Comment by brianburridge** [comment]
@DianaDryerDavis I guess what you meant by your comment this afternoon is that you haven't created all the relationships yet? For example, Your code says that a plant belongs to a row, but there is no foreign key to rows from plants.

**Comment by DianaDryerDavis** [comment]
Oh, I thought I did that right. I put in belongs_to and has_many, but I must have missed something.

**Comment by DianaDryerDavis** [comment]
@brianburridge Completed for real this time.

**Comment by brianburridge** [comment]
Closer, but still missing two things. First, see bullet 4 above. Second, though you have the _belongs_to side, you haven't added in the other side of the association to the models.

**Comment by DianaDryerDavis** [comment]
Oh, shoot. When I was rolling back and deleting and such to fix my foreign key problems, I accidentally wiped out the validations. They are back in there now.

**Comment by brianburridge** [comment]
Oh, yes. I remember seeing those before. :+1:
