### ISSUE TITLE
Seed Data and Image Uploading

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#37]
_This is assignment 36 and is due on Feb 24, 2015._

* Add some seed data to assignment 35 using the Faker gem.
* Add image upload support to your Rails app from assignment 35, using [CarrierWave gem](https://github.com/carrierwaveuploader/carrierwave).
* You can add image uploads to any existing models in that app.
* For this assignment, use _file_ storage.
* Your user should be able to browse for a local image and upload it along with your other model attributes in the form.
* The uploaded images should show on both the index page (thumbnail size) and the show page (a larger size).
* Feel free to experiment with sizes and versions.
* Please include the URL to your Github repo for this app in a comment in this issue.
* Note: do not deploy this to Heroku yet

**Comment by DianaDryerDavis** [comment]
https://github.com/DianaDryerDavis/kid_art

**Comment by DianaDryerDavis** [comment]
All of the links work -- no errors! -- but they don't all lead to logical places. Yet. Also, some of the "submit" buttons and other things that are shared between show and edit pages need some if/else work so the display type is accurate. And in places where the photos are clickable links I should put a blue border or something on them so it's obvious. I'll make improvements after I'm done with other assignments.

**Comment by brianburridge** [comment]
Well, links all leading to logical places is nice, but it also falls into UI design. So, while it's a very good thing to strive for and learn, don't feel too bad about it, or get held up by it. Most important right now is learning the Ruby/Rails part. Experience will help give you better UI organization over time.

:+1:
