### ISSUE TITLE
CarrierWave, S3 and environment varaibles

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#38]
_This is assignment 37 and is due on Feb 25, 2015._

* Convert the app from assignment 36 to use [Amazon S3, via Fog](https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3), instead of local file storage.
* Remember to use the [dotenv gem](https://github.com/bkeepers/dotenv) and `heroku config` so you aren't storing your S3 private access keys in GitHub
* Deploy to Heroku (and GitHub as always)
* Please provide the link to the repo AND your Heroku app in a comment here.

**Comment by brianburridge** [comment]
What is the heroku link for this so I can try it out?

**Comment by DianaDryerDavis** [comment]
https://github.com/DianaDryerDavis/kid_art
https://nameless-ocean-9042.herokuapp.com

**Comment by brianburridge** [comment]
:+1:
