### ISSUE TITLE
Using ActiveAdmin for fully customizable, but quick, back-end admins

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#41]
_This is assignment 40 and is due on Feb 26, 2015._

* Add [ActiveAdmin](https://github.com/activeadmin/activeadmin) to your current application
* Review the [documentation](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md)
* Create an active admin resource for every model in your app
* Do some customization
* Ensure all forms save and allow the user to set the relationships
* Deploy to Heroku
* Paste the link to your Heroku app in a comment here for my review

**Comment by DianaDryerDavis** [comment]
https://nameless-ocean-9042.herokuapp.com

**Comment by brianburridge** [comment]
@DianaDryerDavis you are missing some setup to get the active admin resources working. Try editing one of the models with it. (All have the same problem). This is bullet 6.

**Comment by DianaDryerDavis** [comment]
@brianburridge I don't know what "bullet 6" means. Which part did I mess up?

**Comment by DianaDryerDavis** [comment]
Oh ... just got ForbiddenAttributesError. I don't know what that means but I'll look into it.

**Comment by brianburridge** [comment]
The 6th bullet point of the assignment.

**Comment by DianaDryerDavis** [comment]
D'oh!

**Comment by brianburridge** [comment]
:+1:
