### ISSUE TITLE
Restricting ActiveAdmin access

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#45]
_This is assignment 44 and is due on Mar 05, 2015._

* Adjust your Pinterest app to only allow "admin" users to access the /admin section

**Comment by DianaDryerDavis** [comment]
Nope, not on Pinterest. On kid_art. http://nameless-ocean-9042.herokuapp.com

**Comment by brianburridge** [comment]
Already seen it in person. :)
