### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#49]
_This is assignment 48 and is due on Mar 11, 2015._

* Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
* Try [Dash](http://kapeli.com/dash)
* Try [OmniRef](https://www.omniref.com/)
* Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
* Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
* Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
* Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by DianaDryerDavis** [comment]
Did this:

class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]
  before_action :set_children_for_this_user, only: [:new, :edit, :update, :create]

  # GET /children
  # GET /children.json
  def index
    @children = Child.where(user: @current_user)
    logger.debug {"The current user's email address: #{@current_user.email}"}

  end

To get this in the log:

Started GET "/children" for 127.0.0.1 at 2015-03-16 13:47:16 -0400
Processing by ChildrenController#index as HTML
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "guest@guest.com"]]
The current user's email address: guest@guest.com
  Child Load (0.7ms)  SELECT "children".* FROM "children" WHERE "children"."user_id" = 1
  Artwork Load (0.6ms)  SELECT  "artworks".* FROM "artworks" WHERE "artworks"."child_id" = $1  ORDER BY "artworks"."id" ASC LIMIT 1  [["child_id", 951]]

Did this:

class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:pick_the_medium, :show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    if params[:child_id]
      @artworks = Artwork.where(child_id: params[:child_id])
      @thischild = Child.find(params[:child_id])

      logger.debug "All this child's artworks: #{@artworks.inspect}"

    elsif params[:id]
      @artworks = Artwork.where(id: params[:id])
    else
      @artworks = Artwork.all
    end
  end

to get this in the log:

Started GET "/artworks?child_id=953" for 127.0.0.1 at 2015-03-16 13:49:52 -0400
Processing by ArtworksController#index as HTML
  Parameters: {"child_id"=>"953"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "guest@guest.com"]]
  Child Load (0.4ms)  SELECT  "children".* FROM "children" WHERE "children"."id" = $1 LIMIT 1  [["id", 953]]
  Artwork Load (0.5ms)  SELECT "artworks".* FROM "artworks" WHERE "artworks"."child_id" = $1  [["child_id", 953]]
All this child's artworks: #<ActiveRecord::Relation [#<Artwork id: 1934, grade: "6", created_at: "2015-03-16 16:50:33", updated_at: "2015-03-16 16:50:33", child_id: 953, comment: "Maxime sint quae assumenda officiis nostrum animi.", pic: "cats.jpeg", medium_id: 607>, #<Artwork id: 1935, grade: "5", created_at: "2015-03-16 16:50:34", updated_at: "2015-03-16 16:50:34", child_id: 953, comment: "Facere est est quo blanditiis id nesciunt ut.", pic: "cats.jpeg", medium_id: 595>]>
  Medium Load (0.7ms)  SELECT  "media".* FROM "media" WHERE "media"."id" = $1 LIMIT 1  [["id", 607]]
  Medium Load (0.3ms)  SELECT  "media".* FROM "media" WHERE "media"."id" = $1 LIMIT 1  [["id", 595]]

**Comment by DianaDryerDavis** [comment]
I added debug statements to ChildrenController#index and ArtworksController#index.

**Comment by brianburridge** [comment]
:+1:
