### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [DianaDryerDavis/Assignments#7]
_This assignment is due on Jan 28, 2015._

* Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
* Run the code and paste the output into your issue as a comment for this assignment
* It should list all the proper class names and all class tests should result in 'true'
* Before you run it, can you guess what will happen with the constant code you've created?

**Comment by DianaDryerDavis** [comment]
dianas-air:assignments dianadavis$ ruby assignment07.rb 
String
Date
Fixnum
Array
Array
Hash
true
true
true
true
true
true
String
Fixnum
Array
Hash
Symbol
assignment07.rb:61: warning: already initialized constant ALLCAPS
assignment07.rb:58: warning: previous definition of ALLCAPS was here
yelling
dianas-air:assignments dianadavis$

**Comment by brianburridge** [comment]
Please no yelling. :smile: 

:+1:
